project:
  type: website
  output-dir: docs

website:
  title: "Landschaftsökologie Bauer"
  description: "Markus Bauer ist ein selbständiger Vegetationskartierer, Landschaftsplaner und Wissenschaftler im Bereich Ökologie in Freising und an der Technischen Universität München. Schwerpunkte sind Monitoring, Biotopkartierung, Renaturierung, GIS-Analysen und Statistik."
  site-url: "https://markus1bauer.github.io/"
  back-to-top-navigation: true
  search: false
  navbar:
    background: "#0d730d"
    foreground: "white"
    color: "white"
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "Forschung/Research"
        href: forschung.qmd
      - text: "Referenzen/References"
        href: referenzen.qmd
      - icon: github
        href: "https://github.com/markus1bauer/markus1bauer.github.io"
  page-footer:
    left:
      - text: <p>&#169; 2025 Markus Bauer</p>
    center:
      - text: "R"
        href: https://www.r-project.org/about.html
      - text: "Quarto"
        href: https://quarto.org/
      - text: "GitHub Pages"
        href: https://pages.github.com/
    right:
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd

format:
  html:
    include-in-header: includes/google-verification.html
    fontsize: 14pt
    monofont: Arial
    toc: FALSE
    meta:
      keywords: ["Markus", "Bauer", "Kartierung", "Vegetation", "Pflanzen", "Ökologie", "München", "Landschaft", "Munich", "ecology", "restoration", "grasslands", "grassland", "dikes", "dike", "vegetation"]
      description: "Markus Bauer ist ein selbständiger Vegetationskartierer, Landschaftsplaner und Wissenschaftler im Bereich Ökologie in Freising und an der Technischen Universität München. Schwerpunkte sind Monitoring, Biotopkartierung, Renaturierung, GIS-Analysen und Statistik."

babelquarto:
  languagecodes:
  - name: de
    text: "Kartierer [DE]"
  - name: en
    text: "Scientist [EN]"
  mainlanguage: 'de'
  languages: ['en']
title-en: "Markus Bauer"
description-en: "Markus Bauer is a freelance vegetation mapper, landscape planner and scientist (postdoctoral researcher) in the field of ecology in Freising and at the Technical University of Munich. He specialises in monitoring, biotope mapping, renaturation, GIS analyses and statistics."
author-en: "Markus Bauer"
lang: de
